# Navigation Links

main:
  - name: Home
    url: '/#about'
    weight: 10
  - name: Posts
    url: '/#posts'
    weight: 20
  - name: 'Glucose Stats'
    url: '/#glucose'
    weight: 40
  - name: Projects
    url: '/#projects'
    weight: 45
  - name: Education
    url: '/#accomplishments'
    weight: 50
  - name: Contact
    url: '/#contact'
    weight: 60
