# Site parameters for dddiaz theme

# SEO
marketing:
  seo:
    site_type: Person
    description: 'Daniel Diaz is a Staff Bioinformatics Engineer specializing in Genomics.'
  analytics:
    google_analytics: 'G-NHQL5ZP442'

# Footer
footer:
  copyright:
    notice: '© {year} Daniel Diaz.'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Features
features:
  syntax_highlighter:
    theme_light: github
    theme_dark: dracula
  avatar:
    shape: circle
