FROM mcr.microsoft.com/devcontainers/go:1-1.23-bookworm

# Overwrite first run notice
RUN rm -f /usr/local/etc/vscode-dev-containers/first-run-notice.txt
COPY first-run-notice.txt /usr/local/etc/vscode-dev-containers/